// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjMfMSnTnmLeebY2IFvlxeNxIGlBpiCPg',
    appId: '1:534376078013:web:16811c9cacb2946440b5d4',
    messagingSenderId: '534376078013',
    projectId: 'day32firebase-auth',
    authDomain: 'day32firebase-auth.firebaseapp.com',
    storageBucket: 'day32firebase-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqGwIAPcIBK8_skRM1TW3nICJ1WJRDS3Q',
    appId: '1:534376078013:android:9e7a37c5500f8ba540b5d4',
    messagingSenderId: '534376078013',
    projectId: 'day32firebase-auth',
    storageBucket: 'day32firebase-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAaPFcMjNJGlUCsY4ITG5e24Co8SDI1us',
    appId: '1:534376078013:ios:397db1c7f3fcd70140b5d4',
    messagingSenderId: '534376078013',
    projectId: 'day32firebase-auth',
    storageBucket: 'day32firebase-auth.firebasestorage.app',
    iosClientId: '534376078013-r50m1v66j1h2bah67srvqg29m37qjca4.apps.googleusercontent.com',
    iosBundleId: 'com.example.day32FirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAaPFcMjNJGlUCsY4ITG5e24Co8SDI1us',
    appId: '1:534376078013:ios:397db1c7f3fcd70140b5d4',
    messagingSenderId: '534376078013',
    projectId: 'day32firebase-auth',
    storageBucket: 'day32firebase-auth.firebasestorage.app',
    iosClientId: '534376078013-r50m1v66j1h2bah67srvqg29m37qjca4.apps.googleusercontent.com',
    iosBundleId: 'com.example.day32FirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjMfMSnTnmLeebY2IFvlxeNxIGlBpiCPg',
    appId: '1:534376078013:web:62e0adacc67c04f740b5d4',
    messagingSenderId: '534376078013',
    projectId: 'day32firebase-auth',
    authDomain: 'day32firebase-auth.firebaseapp.com',
    storageBucket: 'day32firebase-auth.firebasestorage.app',
  );

}