// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT8KqBgPxcKc00mT3VrtsfvwT_vIY2LKk',
    appId: '1:1002528671874:web:edc84d45fed36e4f458c9b',
    messagingSenderId: '1002528671874',
    projectId: 'day34firebase-push-notif',
    authDomain: 'day34firebase-push-notif.firebaseapp.com',
    storageBucket: 'day34firebase-push-notif.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtE3mm9vOYxlHFOmVRQQwZprjTex-6b14',
    appId: '1:1002528671874:android:02e597ea1a129202458c9b',
    messagingSenderId: '1002528671874',
    projectId: 'day34firebase-push-notif',
    storageBucket: 'day34firebase-push-notif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuucNR2sz1pcYZNu7z96kJU6QsEP5Pq68',
    appId: '1:1002528671874:ios:535e3619fc629aff458c9b',
    messagingSenderId: '1002528671874',
    projectId: 'day34firebase-push-notif',
    storageBucket: 'day34firebase-push-notif.firebasestorage.app',
    iosBundleId: 'com.example.day34PushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuucNR2sz1pcYZNu7z96kJU6QsEP5Pq68',
    appId: '1:1002528671874:ios:535e3619fc629aff458c9b',
    messagingSenderId: '1002528671874',
    projectId: 'day34firebase-push-notif',
    storageBucket: 'day34firebase-push-notif.firebasestorage.app',
    iosBundleId: 'com.example.day34PushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT8KqBgPxcKc00mT3VrtsfvwT_vIY2LKk',
    appId: '1:1002528671874:web:ddee6ace5515de46458c9b',
    messagingSenderId: '1002528671874',
    projectId: 'day34firebase-push-notif',
    authDomain: 'day34firebase-push-notif.firebaseapp.com',
    storageBucket: 'day34firebase-push-notif.firebasestorage.app',
  );
}
