// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy5jGgum1lHGe_oF9GDcDMPF4xIOuEk1k',
    appId: '1:197273597291:web:06ef167a1433e11a59c82e',
    messagingSenderId: '197273597291',
    projectId: 'day33firebase-firestore',
    authDomain: 'day33firebase-firestore.firebaseapp.com',
    storageBucket: 'day33firebase-firestore.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYdCHspj06ydRUYi1IMbmmF9pS2L9qHgU',
    appId: '1:197273597291:android:36cf17343563299b59c82e',
    messagingSenderId: '197273597291',
    projectId: 'day33firebase-firestore',
    storageBucket: 'day33firebase-firestore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDP5m6ANjF1VfxmlaGLVv-FbQ1uAiAjcY',
    appId: '1:197273597291:ios:ec7286cbd0673e8e59c82e',
    messagingSenderId: '197273597291',
    projectId: 'day33firebase-firestore',
    storageBucket: 'day33firebase-firestore.firebasestorage.app',
    iosBundleId: 'com.example.day33FirebaseFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDP5m6ANjF1VfxmlaGLVv-FbQ1uAiAjcY',
    appId: '1:197273597291:ios:ec7286cbd0673e8e59c82e',
    messagingSenderId: '197273597291',
    projectId: 'day33firebase-firestore',
    storageBucket: 'day33firebase-firestore.firebasestorage.app',
    iosBundleId: 'com.example.day33FirebaseFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy5jGgum1lHGe_oF9GDcDMPF4xIOuEk1k',
    appId: '1:197273597291:web:4a79e45eb6f0738359c82e',
    messagingSenderId: '197273597291',
    projectId: 'day33firebase-firestore',
    authDomain: 'day33firebase-firestore.firebaseapp.com',
    storageBucket: 'day33firebase-firestore.firebasestorage.app',
  );
}
